export const USER_REGISTER = 'USER_REGISTER'
export const COMPANY_REGISTER = 'COMPANY_REGISTER'
export const LOGIN = 'LOGIN'
export const ADD_TICKET = 'ADD_TICKET'
export const USER_TICKET_REPORT = "USER_TICKET_REPORT"
